### ISSUE TITLE
This code causes a null arg exception

### ISSUE THREAD

**Issue by njbrown09** [RevenantX/LiteNetLib#219]
Im getting a nullargumentexception. Here is the error

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at LiteNetLib.Utils.NetDataReader.GetInt()
   at LiteNetTest.Program.<>c.<Server>b__1_2(NetPeer fromPeer, NetPacketReader dataReader, DeliveryMethod deliveryMethod) in D:\Git Repositories\LiteNetTest\LiteNetTest\Program.cs:line 60
   at LiteNetLib.EventBasedNetListener.LiteNetLib.INetEventListener.OnNetworkReceive(NetPeer peer, NetPacketReader reader, DeliveryMethod deliveryMethod)
   at LiteNetLib.NetManager.ProcessEvent(NetEvent evt)
   at LiteNetLib.NetManager.PollEvents()
   at LiteNetTest.Program.Server() in D:\Git Repositories\LiteNetTest\LiteNetTest\Program.cs:line 66
   at LiteNetTest.Program.Main(String[] args) in D:\Git Repositories\LiteNetTest\LiteNetTest\Program.cs:line 16

```

```csharp
using System;
using System.Threading;
using LiteNetLib;
using LiteNetLib.Utils;

namespace LiteNetTest
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            ConsoleKeyInfo i = Console.ReadKey();

            if (i.KeyChar == 's')
            {
                Server();
            }
            else
            {
                for (int ii = 0; ii < 100; ii++)
                {
                    new Thread(() =>
                    {
                        Thread.CurrentThread.IsBackground = true;
                        Client();

                    }).Start();
                }
                while (true)
                {
                   
                }
            }
        }

        private static void Server()
        {
            EventBasedNetListener listener = new EventBasedNetListener();
            NetManager server = new NetManager(listener);
            server.Start(9050 /* port */);

            listener.ConnectionRequestEvent += request =>
            {
                if(server.PeersCount < 1000 /* max connections */)
                    request.AcceptIfKey("SomeConnectionKey");
                else
                    request.Reject();
            };

            listener.PeerConnectedEvent += peer =>
            {
                Console.WriteLine("We got connection: {0}", peer.EndPoint); // Show peer ip
                NetDataWriter writer = new NetDataWriter();                 // Create writer class
                writer.Put("Hello client!");                                // Put some string
                peer.Send(writer, DeliveryMethod.ReliableOrdered);             // Send with reliability
            };
            
            listener.NetworkReceiveEvent += (fromPeer, dataReader, deliveryMethod) =>
            {
                Console.WriteLine("We got: {0}", dataReader.GetInt());
                dataReader.Recycle();
            };

            while (!Console.KeyAvailable)
            {
                server.PollEvents();
                Thread.Sleep(15);
            }
            server.Stop();
        }


        private static void Client()
        {
            EventBasedNetListener listener = new EventBasedNetListener();
            NetManager client = new NetManager(listener);
            client.Start();
            client.Connect("localhost" /* host ip or name */, 9050 /* port */, "SomeConnectionKey" /* text key or NetDataWriter */);
            listener.NetworkReceiveEvent += (fromPeer, dataReader, deliveryMethod) =>
            {
                Console.WriteLine("We got: {0}", dataReader.GetString(100 /* max length of string */));
                dataReader.Recycle();
            };

            while (!Console.KeyAvailable)
            {
                client.PollEvents();
                NetDataWriter writer = new NetDataWriter();                 // Create writer class
                writer.Put(101);                                // Put some string
                client.SendToAll(writer, DeliveryMethod.ReliableOrdered);   
                Thread.Sleep(15);
            }

            client.Stop();
        }
    }
}
```

**Library version**: Master Branch from 20 mins ago.

**Framework**: >NET 4.7.2

**OS**: Windows

**Comment by RevenantX** [comment]
@njbrown09 thanks for bug report! There was problem with NetPacketReader recycle method.

**Comment by RevenantX** [comment]
Fixed!)

**Comment by njbrown09** [comment]
Fix confirmed. Thanks for being so fast!
