### ISSUE TITLE
Crash on NetManager.Start

### ISSUE THREAD

**Issue by SynergiAios** [RevenantX/LiteNetLib#268]
I have an simple issue, I wanted to give the netstandard 2.0 Version of LiteNetLib a try, but I got an instant issue when starting.

**Error**:System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_DontFragment(Boolean value)
   at LiteNetLib.NetSocket.Bind(IPAddress addressIPv4, IPAddress addressIPv6, Int32 port, Boolean reuseAddress) in E:\Projects\LiteNetLib\LiteNetLib\NetSocket.cs:line 105
   at LiteNetLib.NetManager.Start(IPAddress addressIPv4, IPAddress addressIPv6, Int32 port) in E:\Projects\LiteNetLib\LiteNetLib\NetManager.cs:line 821
   at LiteNetLib.NetManager.Start(Int32 port) in E:\Projects\LiteNetLib\LiteNetLib\NetManager.cs:line 848
   at Aviga.Networking.Router.Connect(EventBasedNetListener listener, Peer peer, String configPath) in /Users/synergi/repos/Aviga.Networking/Aviga.Networking/Router.cs:line 57
   at Aviga.Networking.Peer.Start() in /Users/synergi/repos/Aviga.Networking/Aviga.Networking/Peer.cs:line 90
   at Aviga.Networking.Peer.RunStandalone() in /Users/synergi/repos/Aviga.Networking/Aviga.Networking/Peer.cs:line 47
   at Aviga.Networking.Server.Server.RunStandalone() in /Users/synergi/repos/Aviga.Networking/Aviga.Networking.Server/Server.cs:line 16
   at Aviga.Networking.Server.Test.Program.Main(String[] args) in /Users/synergi/repos/Aviga.Networking/Aviga.Networking.Server.Test/Program.cs:line 10

```csharp
//Some c# code if needed
netPeer.Connect("192.168.0.1", 9050);
```

**Library version**: 0.8.1.1-beta

**Framework**: dotnetStandard 2.0, dotnet Core 2.1

**OS**: MacOs

**Comment by SynergiAios** [comment]
To be quite honest, I don't understand why this exception even raises. Checking your code, you have a try catch around it.

```csharp
            if (socket.AddressFamily == AddressFamily.InterNetwork)
            {
                socket.Ttl = NetConstants.SocketTTL;
                
                try { socket.DontFragment = true; }
                catch (SocketException e)
                {
                    NetUtils.DebugWriteError("[B]DontFragment error: {0}", e.SocketErrorCode);
                }

                try { socket.EnableBroadcast = true; }
                catch (SocketException e)
                {
                    NetUtils.DebugWriteError("[B]Broadcast error: {0}", e.SocketErrorCode);
                }
            }
```

**Comment by SynergiAios** [comment]
Further Investigations, using the current nuget package 0.8.1.1-beta, this issue occurs. Using the current version of the repo and using a project reference and not a nuget package, the behaviour is as expected. The try-catch block triggers and puts into the logger, that the dontFragment is not supported. It doesn't crash any further and keeps running. Any Idea on this strange behaviour?

**Comment by RevenantX** [comment]
@SynergiAios seems that this is some specific ios/netcore bug.

**Comment by RevenantX** [comment]
@SynergiAios fixed

**Comment by SynergiAios** [comment]
@RevenantX just saw it, thx awesome.

**Comment by SynergiAios** [comment]
It so sad, written in Net Standard, and still have to insert special rules for MacOS. Whom to blame here would be interesting for me :) (Apple or Microsoft?)

**Comment by RevenantX** [comment]
@SynergiAios i think both)
