### ISSUE TITLE
Cant accept connections with UnsyncedEvents enabled

### ISSUE THREAD

**Issue by aizuon** [RevenantX/LiteNetLib#369]
Can't accept incoming connections on netcore 3.1 server. Same code used to work before when server was a Unity project.

edit: Disabling UnsyncedEvents fixes the issue.

```csharp
private void Listener_ConnectionRequestEvent(ConnectionRequest request)
{
    Logger.Information($"Incoming connection from {request.RemoteEndPoint}");
    if (Server.ConnectedPeersCount < 1337)
        request.AcceptIfKey($"{Id}/HUB");
    else
        request.Reject();
}
```

Using AcceptIfKey or Accept doesn't matter, I always get the same exception

exception:
System.Threading.LockRecursionException
  HResult=0x80131500
  Message=Recursive upgradeable lock acquisitions not allowed in this mode.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.EnterUpgradeableReadLock()
   at LiteNetLib.NetManager.OnConnectionSolved(ConnectionRequest request, Byte[] rejectData, Int32 start, Int32 length)
   at LiteNetLib.ConnectionRequest.AcceptIfKey(String key)
   at Zin.Hub.Networking.HubServer.Listener_ConnectionRequestEvent(ConnectionRequest request) in C:\Users\dorq\source\repos\zin\Server\Zin.Hub\Networking\HubServer.cs:line 84
   at LiteNetLib.EventBasedNetListener.LiteNetLib.INetEventListener.OnConnectionRequest(ConnectionRequest request)
   at LiteNetLib.NetManager.ProcessEvent(NetEvent evt)
   at LiteNetLib.NetManager.CreateEvent(EType type, NetPeer peer, IPEndPoint remoteEndPoint, SocketError errorCode, Int32 latency, DisconnectReason disconnectReason, ConnectionRequest connectionRequest, DeliveryMethod deliveryMethod, NetPacket readerSource, Object userData)
   at LiteNetLib.NetManager.ProcessConnectRequest(IPEndPoint remoteEndPoint, NetPeer netPeer, NetConnectRequestPacket connRequest)
   at LiteNetLib.NetManager.DataReceived(Byte[] reusableBuffer, Int32 count, IPEndPoint remoteEndPoint)
   at LiteNetLib.NetManager.LiteNetLib.INetSocketListener.OnMessageReceived(Byte[] data, Int32 length, SocketError errorCode, IPEndPoint remoteEndPoint)

**Library version**: commit 0e5880b6e933f6e3d80a1efd359cc84cfa75a29a on client, 0.9.2.2 on server

**Framework**: Unity on client, netcore 3.1 on server

**OS**: Windows

**Comment by tylerohlsen** [comment]
@RevenantX I'm running into the same issue.  Why was this closed?  Disabling UnsyncedEvents is only a workaround, not a fix.

**Comment by RevenantX** [comment]
@tylerohlsen  "closed this in d3ee215 on May 20" because it's fixed in master branch.

**Comment by tylerohlsen** [comment]
@RevenantX awesome, thanks for the confirmation!  Do you have a plan for when the next nuget release will be?

**Comment by RevenantX** [comment]
@tylerohlsen no, but maybe soon after some mini improvements.
