### ISSUE TITLE
iOS Crash with Unity 2020

### ISSUE THREAD

**Issue by chiedozi** [RevenantX/LiteNetLib#392]
Building and deploying a Unity project to iOS will result in a crash when a connection is attempted. It seems to stem from this issue: https://issuetracker.unity3d.com/issues/ios-player-crashes-with-litenetbugmain-when-accessing-ipinterfaceproperties-dot-gatewayaddresses.

In 2020.1.0f1, if IPInterfaceProperties.GatewayAddresses is used, the iOS Player will crash with:
```
Thread 1 Queue : com.apple.main-thread (serial)
#0    0x0000000104d7f4b8 in il2cpp::icalls::System::System::Net::NetworkInformation::MacOsIPInterfaceProperties::ParseRouteInfo_internal(Il2CppString*, Il2CppArray**) ()
#1    0x0000000104e7c95c in MacOsIPInterfaceProperties_get_GatewayAddresses_m1DA309123026DC1EA712DC469FACF97E94C853C2 ()
#2    0x0000000104dd95f4 in Test_GetLocalIP_mB4CF5A5682B9802067BC179FAD2F8D326A1A1910 ()
#3    0x0000000104838cac in RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**) ()
#4    0x0000000104dc110c in il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) ()
#5    0x0000000104ad03a4 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) ()
#6    0x0000000104ad946c in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) ()
#7    0x0000000104ae53f4 in MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingExceptionPtr*) ()
#8    0x0000000104ae5678 in MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) ()
#9    0x0000000104ae4030 in MonoBehaviour::DelayedStartCall(Object*, void*) ()
#10    0x00000001049ae2cc in DelayedCallManager::Update(int) ()
#11    0x0000000104a2c3c0 in ExecutePlayerLoop(NativePlayerLoopSystem*) ()
#12    0x0000000104a2c3f4 in ExecutePlayerLoop(NativePlayerLoopSystem*) ()
#13    0x0000000104a2c64c in PlayerLoop() ()
#14    0x0000000104c135f4 in UnityPlayerLoopImpl(bool) ()
#15    0x0000000104816b98 in UnityRepaint ()
#16    0x0000000104816a74 in -[UnityAppController(Rendering) repaintDisplayLink] ()
#17    0x000000018d819fac in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#18    0x000000018d8e4fbc in display_timer_callback(__CFMachPort*, void*, long, void*) ()
```

From what I can tell, this is a Unity regression, as it doesn't crash in Unity 2019.4. I was just wondering if you are aware of any workaround that can be done while they fix this, as this seems to be called as part of the connect flow.

```csharp
public class Test : MonoBehaviour
{
    void Start()
    {
        GetLocalIP();
    }

    public static void GetLocalIP() {
        var targetList = new List<string>();
        try
        {
            foreach (var ni in NetworkInterface.GetAllNetworkInterfaces())
            {
                if (ni.NetworkInterfaceType == NetworkInterfaceType.Loopback || 
                    ni.OperationalStatus != OperationalStatus.Up)
                    continue;

                var ipProps = ni.GetIPProperties();

                // THIS LINE WILL CRASH
                if (ipProps.GatewayAddresses.Count == 0)
                    continue;

                foreach (var ip in ipProps.UnicastAddresses)
                {
                    var address = ip.Address;
                    if (address.AddressFamily == AddressFamily.InterNetwork)
                        targetList.Add(address.ToString());
                }
            }
        }
        catch {
            // No op
        }
        
        Debug.Log(string.Join(",", targetList));
    }
}
```

**Library version**: latest (f01cca3eb9bc3c135787ea2ec2443b45c35d4d2e)

**Framework**: Unity

**OS**: iOS

**Comment by RevenantX** [comment]
@chiedozi GetLocalIp isn't used in connection code, only in NatPunchModule.

**Comment by chiedozi** [comment]
Ah, you're right. Sorry, it was one of my local edits that was calling this code. I will close this as it's a bug on the Unity side. Thanks!
